/* automatically generated by sed scripts from the c source named below: */
#ifndef  __CDDSTD_HF
#define  __CDDSTD_HF

void *ddf_malloc(size_t size);
void *ddf_calloc(size_t nmemb, size_t size);
void ddf_scanf(int n, const char *format, ...);
int ddf_fscanf(FILE *stream, int check, int n, const char *format, ...);
void ddf_fgets(char *s, FILE *stream);

#endif  /* __CDD_HF */
/* end of cddlib.h */
